# Generated by Django 6.0.2 on 2026-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='credits/'),
        ),
    ]
